name: Repository Maintenance

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:      # Allow manual triggers

jobs:
  repo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check Repository Standards
        run: |
          # Check for essential files
          files_to_check=("README.md" "LICENSE" ".gitignore" "CONTRIBUTING.md")
          missing_files=()
          
          for file in "${files_to_check[@]}"; do
            if [ ! -f "$file" ]; then
              missing_files+=("$file")
            fi
          done
          
          if [ ${#missing_files[@]} -ne 0 ]; then
            echo "Missing essential files: ${missing_files[*]}"
            exit 1
          fi

      - name: Verify README Content
        run: |
          if [ -f "README.md" ]; then
            required_sections=("Introduction" "Installation" "Usage" "Contributing" "Architecture")
            missing_sections=()
            
            for section in "${required_sections[@]}"; do
              if ! grep -i "^#.*${section}" README.md > /dev/null; then
                missing_sections+=("$section")
              fi
            done
            
            if [ ${#missing_sections[@]} -ne 0 ]; then
              echo "README.md missing sections: ${missing_sections[*]}"
              exit 1
            fi
          fi

      - name: Check TypeScript Configuration
        run: |
          if [ -f "package.json" ]; then
            if ! grep -q '"typescript"' package.json; then
              echo "TypeScript dependency not found"
              exit 1
            fi
            
            if [ ! -f "tsconfig.json" ]; then
              echo "Missing TypeScript configuration"
              exit 1
            fi
          fi

      - name: Check Testing Setup
        run: |
          if [ -f "package.json" ]; then
            if ! grep -q '"jest"' package.json && ! grep -q '"mocha"' package.json; then
              echo "No testing framework found"
              exit 1
            fi
            
            if [ ! -d "__tests__" ] && [ ! -d "tests" ]; then
              echo "No test directory found"
              exit 1
            fi
          fi

      - name: Create Issue for Missing Requirements
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Repository Maintenance Required',
              body: `Repository maintenance check failed. Please address the following:
              
              - Ensure all essential files are present (README.md, LICENSE, .gitignore, CONTRIBUTING.md)
              - Verify README.md contains all required sections
              - Configure TypeScript if not present
              - Set up testing framework and directory
              - Add architecture diagrams
              - Ensure mobile optimization
              - Implement dark neon theme with cyan/magenta gradients
              - Add visual assets and screenshots
              
              Please review the workflow logs for specific details.`
            });
